### ISSUE TITLE
Also include schedules for "Standalone Containers"

### ISSUE THREAD

**Issue by dirkdevriendt** [SocialEngine/rancher-cron#10]
Great project!
For one of our services, I added a container manually with the appropriate schedule config label, but was surprised to see it did not get picked up.
I'm assuming this is because rancher-cron queries for services and containers in those services, causing the Standalone Containers to not get listed, but I haven't dug in too much so I may be mistaken...

**Comment by smazurov** [comment]
That is correct. I believe thats a limitation of rancher api - we query each service to see if they have the right label, then we find container with that label. You can see this in action [here](https://github.com/SocialEngine/rancher-cron/blob/master/metadata/metadata.go#L64-L66). From when I looked at rancher metadata api last, there was not an equivalent container-level lookup.

Meaning, we cannot query rancher api directly for containers with that label, thus standalone containers will not be picked up. Only way I see to make it happen is to loop through all containers, which is too costly.

Any reason why you cannot create a stack with a single `start-once` service?

**Comment by dirkdevriendt** [comment]
No reason at all, I was  just wondering if I was understanding it correctly (and if other people encounter the same thing, they may find this message).
It could be added as an optional setting at some point, but I understand the performance cost could be prohibitive for large clusters and as you say, it is easy to work around.
Thanks for taking the time to reply!

**Comment by smazurov** [comment]
No problem. Easy fix would be to lookup containers by label instead of service, but that would be on rancher api side. Closing for now, but thanks for your interest!
