### ISSUE TITLE
Queries all services not just it's own stack

### ISSUE THREAD

**Issue by pschrammel** [SocialEngine/rancher-cron#11]
We deployed the same stack several times rancher-cron in each of them. 

The problem now is that rancher-cron uses getServices() so it seems to register cron entries multiple times (over all stacks, not just for it's own).

Schouldn't it just care about it's own stack?

**Comment by smazurov** [comment]
By design it looks at all stacks - you only need to run 1 copy of this service per environment.

**Comment by pschrammel** [comment]
I see (perhaps mention this in the docs). Though it's hard to express this kind of dependencies in rancher (a stack should be self contained). Thanks anyways, nice piece of code.

**Comment by smazurov** [comment]
I went for the design employed by rancher itself -  you only run 1 dns service, or registry update service per environment. Seemed fitting to just run one copy. 

I would personally be pretty annoyed if I had to have a service for triggering crons, in addition to the service that is running the crons for each of my stacks.

Good idea to update the readme.
