### ISSUE TITLE
How does rancher-cron handle services with scale > 1?

### ISSUE THREAD

**Issue by ghost** [SocialEngine/rancher-cron#12]
I have several cron type jobs that run using rancher-cron.  I recently updated the jobs to allow parallelization since single run times were creeping up.  After I bumped up the scale (to 4) it seems rancher cron only starts one instance each interval.  I see the following in the README:

"You should not have Auto Restart turned on and have scale of 1 for services you wish to run as a cron container."

Is there any reason that scale must be set to 1?  Is there any easy way to start such as task with scale > 1?  

A naive implementation that starts all containers for the service would suffice.  Though if there is concern with backward-compatibility (though not certain if this would be an issue since the docs explicitly stated to use scale = 1 before now) a label like "com.socialengine.rancher-cron.atscale":"true" would also handle the use case.

**Comment by smazurov** [comment]
I actually don't know - in theory it should work, but I haven't tested it (thus `scale=1` in README). [This code](https://github.com/SocialEngine/rancher-cron/blob/master/metadata/metadata.go#L100-L126) grabs container UUIDs to run based on schedule specified in service label, and looking at it, it should work with scale > 1. 

You could try turning `-debug` on to see more verbose output.

**Comment by smazurov** [comment]
that code is also new in `0.2`, so perhaps you have an older version.

**Comment by ghost** [comment]
I pulled the latest version and confirmed that rancher-cron is now starting all containers.
