### ISSUE TITLE
com.socialengine.rancher-cron.schedule @after Service1

### ISSUE THREAD

**Issue by tonybart1337** [SocialEngine/rancher-cron#3]
I don't know if it's possible, but I really need this option.

More specific I just want to run one container after another one has finished.

P.S. It should be a bit hard cuz: Note: The interval does not take the job runtime into account.

**Comment by smazurov** [comment]
I think that would be outside the scope of this package. Additionally, as far as I know, `rancher` doesn't really expose real time APIs all that well, so you'd be stuck with polling the API for status of a container. It might be better to create a meta-service of sorts that simply starts a docker container 1, when its done, it starts docker container 2, etc.
