### ISSUE TITLE
Container is in running state

### ISSUE THREAD

**Issue by badc0re** [SocialEngine/rancher-cron#5]
I have added a cron-job every 20m for a specific container, with the settings to start ones. 

I have the following error:

**Failed to start container: container is not stopped. Currently in [running] state..**

I have checked the container and it is not running, any hints?

**Comment by smazurov** [comment]
Not sure - I have seen this randomly pop up, but this is more of an issue with rancher api than `rancher-cron`. Typically starting the container you're croning manually resolves the issue.

**Comment by smazurov** [comment]
As this simply queries the API to check container running state, I believe the issue should be raised with rancher api maintainers directly.
