### ISSUE TITLE
Cron syntax

### ISSUE THREAD

**Issue by bkuhl** [SocialEngine/rancher-cron#6]
[Wikipedia addresses cron syntax as having 5 columns](https://en.wikipedia.org/wiki/Cron), but the examples in this case have 6 columns.  Can you elaborate on what these columns are?

**Comment by smazurov** [comment]
The first column is for seconds as original format never had to deal with second precision on cron jobs. I have considered limiting to minute precision, but then you would not able to utilize some nice expanded syntax, such as `@every 23min`. If you want to use pure cron expressions, simply add a `0` to the beginning, i.e. `0 * * * * *`. You can read more about format in the [README](https://github.com/SocialEngine/rancher-cron#cron-expression-format)
