### ISSUE TITLE
Predefined schedules issue

### ISSUE THREAD

**Issue by grachevko** [SocialEngine/rancher-cron#7]
I'll try to use predefined expression like:
`com.socialengine.rancher-cron.schedule: '@monthly'`
But get error:
`04.08.2016 20:04:002016/08/04 17:04:00 Unrecognized descriptor: @monthly`
What am I doing wrong?

**Comment by smazurov** [comment]
I tested to see if i could register a container that has `@monthly` schedule, and it worked. 

What does it say in the `info` line? ex:

```
time="2016-08-04T20:31:32Z" level=info msg="adding container to cron" containerName="cron-schedule" containerUUID=8ee694c3-f699-432d-9ab2-367faf2c4238 schedule="@monthly"
```

My thought is quotes are messing it up, but error doesn't fit (it should have quotes around unrecognized descriptor).

If you can share a full `docker-compose.yml`, that might help narrow it down.

**Comment by smazurov** [comment]
Also you can add `-debug` to get more info on what the service is doing.

![screen shot 2016-08-04 at 2 37 02 pm](https://cloud.githubusercontent.com/assets/21636/17417497/ef75f968-5a50-11e6-82e9-2d968bf9b6b6.png)

**Comment by grachevko** [comment]
I added `-debug`, after restart error gone. 

`time="2016-08-04T21:07:01Z" level=info msg="Starting up Rancher Cron service"
time="2016-08-04T21:07:01Z" level=info msg="Healthcheck handler is listening on :8080"
time="2016-08-04T21:07:01Z" level=debug msg="running discovery, found 1 schedule containers"
time="2016-08-04T21:07:01Z" level=info msg="adding container to cron" containerName="letsencrypt_letsencrypt_1" containerUUID=632df707-3523-4f9f-952b-e61937626903 schedule="@monthly"
time="2016-08-04T21:07:30Z" level=debug msg="already have container" cronExpression="@monthly" uuid=632df707-3523-4f9f-952b-e61937626903
time="2016-08-04T21:07:30Z" level=debug msg="running discovery, found 1 schedule containers"`

strangely
